// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8op0N6wb8ppM75-dcH5Rs_qt4Mx3SMU',
    appId: '1:1016319478836:web:e7b55bb036c3c5488c0e61',
    messagingSenderId: '1016319478836',
    projectId: 'chemilens-18b78',
    authDomain: 'chemilens-18b78.firebaseapp.com',
    storageBucket: 'chemilens-18b78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApXdjkY5ND-1ZKHWEQIPoJqEwF9vbC9oc',
    appId: '1:1016319478836:android:9a7014b40c63ee168c0e61',
    messagingSenderId: '1016319478836',
    projectId: 'chemilens-18b78',
    storageBucket: 'chemilens-18b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZaTBUN1NaK3Tqx8xodYfk8YY72FHgVd0',
    appId: '1:1016319478836:ios:ab5468dbc0b452198c0e61',
    messagingSenderId: '1016319478836',
    projectId: 'chemilens-18b78',
    storageBucket: 'chemilens-18b78.firebasestorage.app',
    iosBundleId: 'com.team25.hogehoge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZaTBUN1NaK3Tqx8xodYfk8YY72FHgVd0',
    appId: '1:1016319478836:ios:d1a43e26c2d3ea698c0e61',
    messagingSenderId: '1016319478836',
    projectId: 'chemilens-18b78',
    storageBucket: 'chemilens-18b78.firebasestorage.app',
    iosBundleId: 'com.example.team25App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8op0N6wb8ppM75-dcH5Rs_qt4Mx3SMU',
    appId: '1:1016319478836:web:92a7a3a62a28f67d8c0e61',
    messagingSenderId: '1016319478836',
    projectId: 'chemilens-18b78',
    authDomain: 'chemilens-18b78.firebaseapp.com',
    storageBucket: 'chemilens-18b78.firebasestorage.app',
  );
}
